---
title: "PUMA and County Data, 2023"
output: github_document
---

```{r}
#| label: setup
#| include: FALSE
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#| label: load packages
library(tidyverse)
library(tidycensus)
library(tidylog)
```

# Race/ethnicity variables (B03002)

```{r}
#| label: race-eth

vars_in <- load_variables(year = 2023, dataset = "acs5")

vars_reth <-
  vars_in %>%
  filter(str_starts(name, "B03002_")) %>%
  mutate(label = str_remove_all(label, ":")) %>%
  separate_wider_delim(label, delim = "!!", names = c(NA, NA, "Hisp", "Race1", "Race2"), too_few = "align_start") %>%
  mutate(
    RaceEthShort = case_when(
      Hisp == "Hispanic or Latino" & !is.na(Race1) ~ NA,
      Hisp == "Hispanic or Latino" & is.na(Race1) ~ "Pop_Pct_Hispanic",
      is.na(Hisp) ~ NA,
      !is.na(Race2) ~ NA,
      is.na(Race1) ~ NA,
      Race1 == "White alone" ~ "Pop_Pct_White_NH",
      Race1 == "Black or African American alone" ~ "Pop_Pct_Black_NH",
      Race1 == "American Indian and Alaska Native alone" ~ "Pop_Pct_AIAN_NH",
      Race1 == "Asian alone" ~ "Pop_Pct_Asian_NH",
      Race1 == "Native Hawaiian and Other Pacific Islander alone" ~ "Pop_Pct_NHPI_NH",
      TRUE ~ "Pop_Pct_Other_NH",
    )
  ) %>%
  select(name, Hisp, Race1, RaceEthShort) %>%
  filter(!is.na(RaceEthShort))

vars_reth

dat_reth_puma_in <- get_acs(
  geography = "puma",
  variables = pull(vars_reth, name),
  year = 2023,
  survey = "acs5",
  summary_var = "B03002_001"
) %>%
  mutate(Level = "PUMA")

dat_reth_county_in <- get_acs(
  geography = "county",
  variables = pull(vars_reth, name),
  year = 2023,
  survey = "acs5",
  summary_var = "B03002_001"
) %>%
  mutate(Level = "County")

dat_reth <- bind_rows(dat_reth_puma_in, dat_reth_county_in) %>%
  left_join(vars_reth, by = c("variable" = "name")) %>%
  summarize(
    Pop_Tot = summary_est[1],
    pct = sum(estimate) / Pop_Tot * 100,
    .by = c("GEOID", "NAME", "RaceEthShort", "Level")
  ) %>%
  pivot_wider(id_cols = c("GEOID", "NAME", "Pop_Tot", "Level"), names_from = RaceEthShort, values_from = pct)

dat_reth
```

# Occupancy variables (B25002)

```{r}
#| label: occup
vars_hu <-
  vars_in %>%
  filter(str_starts(name, "B25002_")) %>%
  mutate(label = str_remove_all(label, ":")) %>%
  separate_wider_delim(label, delim = "!!", names = c(NA, NA, "Occupancy"), too_few = "align_start") %>%
  mutate(
    OccShort = case_when(
      Occupancy == "Occupied" ~ "HU_Pct_Occupied",
      Occupancy == "Vacant" ~ "HU_Pct_Vacant",
    )
  ) %>%
  select(name, Occupancy, OccShort) %>%
  filter(!is.na(OccShort))

vars_hu

dat_hu_puma_in <- get_acs(
  geography = "puma",
  variables = pull(vars_hu, name),
  year = 2023,
  survey = "acs5",
  summary_var = "B25002_001"
) %>%
  mutate(Level = "PUMA")

dat_hu_county_in <- get_acs(
  geography = "county",
  variables = pull(vars_hu, name),
  year = 2023,
  survey = "acs5",
  summary_var = "B25002_001"
) %>%
  mutate(Level = "County")

dat_hu <- bind_rows(dat_hu_puma_in, dat_hu_county_in) %>%
  left_join(vars_hu, by = c("variable" = "name")) %>%
  rename(HU_Tot = summary_est) %>%
  mutate(
    pct = estimate / HU_Tot * 100
  ) %>%
  pivot_wider(id_cols = c("GEOID", "NAME", "HU_Tot", "Level"), names_from = OccShort, values_from = pct)

dat_hu
```

# Age variables (S0101)

```{r}
#| label: age
vars_in <- load_variables(year = 2023, dataset = "acs5/subject")

vars_age <- vars_in %>%
  filter(
    str_starts(name, "S0101_"),
    str_detect(label, "Estimate!!Percent!!Total population"),
    str_detect(label, "!!AGE!!") | str_detect(label, "SELECTED AGE CATEGORIES")
  ) %>%
  separate_wider_delim(label, delim = "!!", names = c(NA, NA, NA, "Type", "Range")) %>%
  mutate(
    AgeShort = case_when(
      Range == "Under 5 years" ~ "Pop_Pct_0004",
      Range == "5 to 9 years" ~ "Pop_Pct_0509",
      Range == "10 to 14 years" ~ "Pop_Pct_1014",
      Range == "15 to 17 years" ~ "Pop_Pct_1517",
      Range == "18 to 24 years" ~ "Pop_Pct_1824",
      Range == "25 to 29 years" ~ "Pop_Pct_2544",
      Range == "30 to 34 years" ~ "Pop_Pct_2544",
      Range == "35 to 39 years" ~ "Pop_Pct_2544",
      Range == "40 to 44 years" ~ "Pop_Pct_2544",
      Range == "45 to 49 years" ~ "Pop_Pct_4564",
      Range == "50 to 54 years" ~ "Pop_Pct_4564",
      Range == "55 to 59 years" ~ "Pop_Pct_4564",
      Range == "60 to 64 years" ~ "Pop_Pct_4564",
      Range == "65 to 69 years" ~ "Pop_Pct_6574",
      Range == "70 to 74 years" ~ "Pop_Pct_6574",
      Range == "75 to 79 years" ~ "Pop_Pct_75plus",
      Range == "80 to 84 years" ~ "Pop_Pct_75plus",
      Range == "85 years and over" ~ "Pop_Pct_75plus",
      TRUE ~ NA
    )
  ) %>%
  filter(!is.na(AgeShort)) %>%
  select(-concept) %>%
  arrange(AgeShort)

vars_age

dat_age_puma_in <- get_acs(
  geography = "puma",
  variables = pull(vars_age, name),
  year = 2023,
  survey = "acs5"
) %>%
  mutate(Level = "PUMA")

dat_age_county_in <- get_acs(
  geography = "county",
  variables = pull(vars_age, name),
  year = 2023,
  survey = "acs5"
) %>%
  mutate(Level = "County")

dat_age <- bind_rows(dat_age_puma_in, dat_age_county_in) %>%
  left_join(vars_age, by = c("variable" = "name")) %>%
  summarize(
    pct = sum(estimate),
    .by = c("GEOID", "NAME", "AgeShort", "Level")
  ) %>%
  pivot_wider(id_cols = c("GEOID", "NAME", "Level"), names_from = AgeShort, values_from = pct)

dat_age
```

# Code region and division

Coding is based on: https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

```{r}
#| label: reg-div

state_reg_div <- fips_codes %>%
  as_tibble() %>%
  distinct(STATE = state, state_code) %>%
  filter(STATE %in% c(state.abb, "DC")) %>%
  mutate(
    DIVISION = case_match(
      as.numeric(state_code),
      c(9, 23, 25, 33, 44, 50) ~ "New England",
      c(34, 36, 42) ~ "Middle Atlantic",
      c(18, 17, 26, 39, 55) ~ "East North Central",
      c(19, 20, 27, 29, 31, 38, 46) ~ "West North Central",
      c(10, 11, 12, 13, 24, 37, 45, 51, 54) ~ "South Atlantic",
      c(1, 21, 28, 47) ~ "East South Central",
      c(5, 22, 40, 48) ~ "West South Central",
      c(4, 8, 16, 35, 30, 49, 32, 56) ~ "Mountain",
      c(2, 6, 15, 41, 53) ~ "Pacific"
    ) %>%
      factor(
        levels = c(
          "New England", "Middle Atlantic", "East North Central",
          "West North Central", "South Atlantic", "East South Central",
          "West South Central", "Mountain", "Pacific"
        )
      ),
    REGION = fct_collapse(
      DIVISION,
      Northeast = c("New England", "Middle Atlantic"),
      Midwest = c("East North Central", "West North Central"),
      South = c("South Atlantic", "East South Central", "West South Central"),
      West = c("Mountain", "Pacific")
    )
  ) %>%
  arrange(REGION, DIVISION)

state_reg_div %>% print(n = 51)
```


# Bring data together

```{r}
#| label: join

dat_tog <- dat_reth %>%
  full_join(dat_hu, by = c("GEOID", "NAME", "Level")) %>%
  full_join(dat_age, by = c("GEOID", "NAME", "Level")) %>%
  mutate(state_code = str_sub(GEOID, 1, 2)) %>%
  right_join(state_reg_div, by = "state_code")

puma_2023 <- dat_tog %>%
  filter(Level == "PUMA") %>%
  select(-state_code, -Level) %>%
  select(GEOID, Name = NAME, State = STATE, Region = REGION, Division = DIVISION, everything())

county_2023 <- dat_tog %>%
  filter(Level == "County") %>%
  select(-state_code, -Level) %>%
  select(GEOID, Name = NAME, State = STATE, Region = REGION, Division = DIVISION, everything())
```

# Save data

```{r}
#| label: save-puma
#| message: false
summary(puma_2023)
glimpse(puma_2023)

usethis::use_data(puma_2023, overwrite = TRUE)
```

```{r}
#| label: save-county
#| message: false
summary(county_2023)
glimpse(county_2023)

usethis::use_data(county_2023, overwrite = TRUE)
```

